### PR TITLE
RATEPLUG-205: offline installment calculator: add support for zero percent installment

### PR DESCRIPTION
**Pull request by rommelfreddy**
the same bugfix and pull request as https://github.com/ratepay/php-library/pull/2 but for the offline calculator

### CODE REVIEW

**Comment by rommelfreddy** [comment]
@eiriarte-mendez push :)

**Review by eiriarte-mendez — CHANGES_REQUESTED** [review]
float numbers comparison:
```php
if ($this->_interestRate > 0) {
```
it could be troublesome in some cases.

Risky division by zero:
```php
$installment = $this->_basketAmount / $this->_runtime;
// and
$installment += ($this->_serviceCharge / $this->_runtime);
```

I have an ongoing research on the method `callCalculationByTime()`, so I would ask you not to change it until then... You could instead add the condition earlier:
```php
switch ($subtype) {
            case 'calculation-by-time':
                return ($yourFloatSafeCondition) ? $this->callCalculationByTime() : $this->yourZeroPercentCalculationByTime();
```
it will also help if you write a test case for the new method(s)

**Comment by rommelfreddy** [comment]
hello @eiriarte-mendez 
this is just a *bug fix*. i do not want to refactor *your* sdk. 

my changes are only based on your code. if there are risky operations, you should change them in your sdk with a separate change and not within this bugfix PR.
if you change the operations in the last release, i will change my PR to fit the new code base.

if there are missing tests, please add them, and i will change the tests in this PR as well.

Thank you.

**Comment by eiriarte-mendez** [comment]
feature integrated with #23 and released in v1.6.0

**Pull request closed without merging**
